#!/bin/sh
if [ $1 = "global" ]; then
cat << EOS
{
  "metadata": {
    "api_version": 2.0,
    "salt_enable": false,
    "stretching_number": 0,
    "hash_type": "sha256",
    "result": "success"
  },
  "items": {
    "global": {
      "id": 1001,
      "password": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
      "group_id": 1001,
      "directory": "/home/example",
      "shell": "/bin/sh",
      "gecos": "example",
      "keys": [
        "ssh-rsa xxxxxx"
      ],
      "link_users": null,
      "hash_type": ""
    }
  }
}
EOS
else
cat << EOS
{
  "metadata": {
    "api_version": 2.0,
    "salt_enable": false,
    "stretching_number": 0,
    "hash_type": "sha256",
    "result": "success"
  },
  "items": {
    "example": {
      "id": 1001,
      "password": "ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff",
      "group_id": 1001,
      "directory": "/home/example",
      "shell": "/bin/sh",
      "gecos": "example",
      "keys": [
        "ssh-rsa xxxxxx"
      ],
      "link_users": null,
      "hash_type": "sha512"
    }
  }
}
EOS
fi
