#!/bin/sh
cat << EOS
{
  "metadata": {
    "api_version": 2.0,
    "result": "success"
  },
  "items": {
    "example": {
      "id": 1001,
      "password": "\$6\$w6EbxEef\$kVz1U/4frk1rfeUZym3r8kf1diqcNXbCFx32cmufBb8CvX1yxl1dtJlO.ebfJpHaboYgIVa8tLpC7QmQWkCPQ/",
      "group_id": 1001,
      "directory": "/home/example",
      "shell": "/bin/sh",
      "gecos": "example",
      "keys": [
        "ssh-rsa xxxxxx"
      ],
      "link_users": null
    }
  }
}
EOS
