#!/bin/sh

set -e

case "$1" in

  configure)
    ln -s /usr/lib/$(DEB_HOST_MULTIARCH)/libnss_stns.so /lib/$(DEB_HOST_MULTIARCH)/libnss_stns.so.2
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac
